name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          logout: true

      - name: Build the Docker image
        run: |
          export IMAGE_TAG_BASE=${{ secrets.DOCKERHUB_USER }}/namespace-provisioner
          export VERSION=$(date +%Y%m%d)
          make docker-build docker-push
